/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'
import * as RepoStrongRef from '../../../com/atproto/repo/strongRef.defs.js'

const $nsid = 'org.okazu-diary.material.collectionItem'

type $nsid = typeof $nsid

export { $nsid }

/** Record declaring the inclusion of a single material or a set of materials in a specific collection. */
type Main = {
  $type: 'org.okazu-diary.material.collectionItem'

  /**
   * Reference to the collection record (`org.okazu-diary.feed.collection`).
   */
  collection: l.AtUriString

  /**
   * Reference(s) to a material or set of materials (`org.okazu-diary.material.external`) to be included in the collection.
   */
  subjects: l.AtUriString[]

  /**
   * Remarks on the collection item.
   */
  note?: string

  /**
   * Indicates the human language of the collection item's primary text content, overriding the `lang` property from the actor profile record.
   */
  lang?: l.LanguageString

  /**
   * Reference to an `org.okazu-diary.feed.entry` record or an `org.okazu-diary.material.collectionItem` of another collection from which this collection item is derived.
   */
  via?: RepoStrongRef.Main
  createdAt: l.DatetimeString
}

export type { Main }

/** Record declaring the inclusion of a single material or a set of materials in a specific collection. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    collection: /*#__PURE__*/ l.string({ format: 'at-uri' }),
    subjects: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.string({ format: 'at-uri' }),
      { minLength: 1, maxLength: 16 },
    ),
    note: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 5000, maxGraphemes: 500 }),
    ),
    lang: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'language' }),
    ),
    via: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
        (() => RepoStrongRef.main) as any,
      ),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
