/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

export * from './collectionItem.defs.js'
export type * from './collectionItem.defs.js'
export { main as default } from './collectionItem.defs.js'