/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'

const $nsid = 'org.okazu-diary.material.defs'

type $nsid = typeof $nsid

export { $nsid }

type Tag = {
  $type?: 'org.okazu-diary.material.defs#tag'

  /**
   * The primary text content of the tag.
   */
  value: string
  lang?: l.LanguageString
}

export type { Tag }

const tag = /*#__PURE__*/ l.typedObject<Tag>(
  $nsid,
  'tag',
  /*#__PURE__*/ l.object({
    value: /*#__PURE__*/ l.string({ minLength: 1, maxLength: 256 }),
    lang: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'language' }),
    ),
  }),
)

export { tag }
