/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'
import * as RepoStrongRef from '../../../com/atproto/repo/strongRef.defs.js'
import * as MaterialDefs from './defs.defs.js'
import * as LabelDefs from '../../../com/atproto/label/defs.defs.js'

const $nsid = 'org.okazu-diary.material.external'

type $nsid = typeof $nsid

export { $nsid }

/** A descriptor of a pornographic material. */
type Main = {
  $type: 'org.okazu-diary.material.external'

  /**
   * URI of the material, typically an HTTP(S) URL. If the URL is of a Web interface for an AT resource (such as a `bsky.app` URL), the record should also include the `record` property referencing the AT resource.
   */
  uri?: l.UriString

  /**
   * Reference to a record representing the material, such as a Bluesky post.
   */
  record?: RepoStrongRef.Main

  /**
   * Title of the material, typically taken from the material's HTML `<title>` element.
   */
  title?: string
  author?: Profile

  /**
   * Description of the material, typically taken from the material's HTML metadata.
   */
  description?: string

  /**
   * Link to a thumbnail of the material, typically taken from the material's HTML metadata.
   */
  thumb?: Thumb

  /**
   * User-specified tags for the material.
   */
  tags?: MaterialDefs.Tag[]

  /**
   * User-specified self-label values for the material. While the Lexicon by its nature assumes the material to be possibly sensitive by default, these label values are intended to signal that a warning should be put on the material even for the explicit Okazu-Diary.org application users who are willing to see mature contents in general.
   */
  labels?: l.$Typed<LabelDefs.SelfLabels> | l.Unknown$TypedObject

  /**
   * General-purpose self-label values primarily for consumption by generic AT clients who may not expect the sensitive nature of this Lexicon. Publishers of this record are strongly recommended to always include at least one of the protocol-global label values; namely, `porn`, `sexual`, `graphic-media`, and `nudity`, unless the material and tags are all known to be safe by themselves. It is the safest to unconditionally include the `sexual` value, which has the `adultOnly` semantics, but it is acceptable to use a stronger (`porn`/`graphic-media`) or more moderate (`nudity`) value instead if the user decides so.
   */
  genericLabels?: l.$Typed<LabelDefs.SelfLabels> | l.Unknown$TypedObject

  /**
   * Indicates the human language of the material's primary text content and default language for material tags, overriding the `lang` property from the actor profile record.
   */
  lang?: l.LanguageString

  /**
   * Reference to an `org.okazu-diary.feed.material` record from another repository from which this collection item is derived. Clients can use this property to offer the user to update this record if the original record have updated from the referenced version.
   */
  via?: RepoStrongRef.Main
}

export type { Main }

/** A descriptor of a pornographic material. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    uri: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'uri' })),
    record: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
        (() => RepoStrongRef.main) as any,
      ),
    ),
    title: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    author: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<Profile>((() => profile) as any),
    ),
    description: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    thumb: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<Thumb>((() => thumb) as any),
    ),
    tags: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<MaterialDefs.Tag>((() => MaterialDefs.tag) as any),
        { maxLength: 64 },
      ),
    ),
    labels: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.typedUnion(
        [
          /*#__PURE__*/ l.typedRef<LabelDefs.SelfLabels>(
            (() => LabelDefs.selfLabels) as any,
          ),
        ],
        false,
      ),
    ),
    genericLabels: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.typedUnion(
        [
          /*#__PURE__*/ l.typedRef<LabelDefs.SelfLabels>(
            (() => LabelDefs.selfLabels) as any,
          ),
        ],
        false,
      ),
    ),
    lang: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'language' }),
    ),
    via: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
        (() => RepoStrongRef.main) as any,
      ),
    ),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Link to an external profile of a person or an entity. */
type Profile = {
  $type?: 'org.okazu-diary.material.external#profile'

  /**
   * Name of the person.
   */
  name?: string

  /**
   * URI of the person, typically an HTTP(S) URL of a profile page.
   */
  uri: l.UriString

  /**
   * Reference to a record representing the profile, such as a Bluesky profile.
   */
  record?: RepoStrongRef.Main

  /**
   * Link to the profile image of the person.
   */
  avatar?: Avatar
}

export type { Profile }

/** Link to an external profile of a person or an entity. */
const profile = /*#__PURE__*/ l.typedObject<Profile>(
  $nsid,
  'profile',
  /*#__PURE__*/ l.object({
    name: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    uri: /*#__PURE__*/ l.string({ format: 'uri' }),
    record: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
        (() => RepoStrongRef.main) as any,
      ),
    ),
    avatar: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<Avatar>((() => avatar) as any),
    ),
  }),
)

export { profile }

type Avatar = {
  $type?: 'org.okazu-diary.material.external#avatar'
  image: Thumb
  style?: 'rounded' | l.UnknownString
}

export type { Avatar }

const avatar = /*#__PURE__*/ l.typedObject<Avatar>(
  $nsid,
  'avatar',
  /*#__PURE__*/ l.object({
    image: /*#__PURE__*/ l.ref<Thumb>((() => thumb) as any),
    style: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string<{ knownValues: ['rounded'] }>(),
    ),
  }),
)

export { avatar }

type Thumb = {
  $type?: 'org.okazu-diary.material.external#thumb'
  cid?: l.CidString
  url: l.UriString
}

export type { Thumb }

const thumb = /*#__PURE__*/ l.typedObject<Thumb>(
  $nsid,
  'thumb',
  /*#__PURE__*/ l.object({
    cid: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'cid' })),
    url: /*#__PURE__*/ l.string({ format: 'uri' }),
  }),
)

export { thumb }
