/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'
import * as RepoStrongRef from '../../../com/atproto/repo/strongRef.defs.js'
import * as LabelDefs from '../../../com/atproto/label/defs.defs.js'
import * as MaterialDefs from '../material/defs.defs.js'

const $nsid = 'org.okazu-diary.feed.entry'

type $nsid = typeof $nsid

export { $nsid }

/** A diary entry to record a self-gratification activity. */
type Main = {
  $type: 'org.okazu-diary.feed.entry'

  /**
   * User-defined date and time associated with the activity, typically the datetime of the climax of the activity or simply of the record creation. The string format must satisfy all the requirements of the `datetime` format from the Lexicon language, except the requirement of whole seconds precision, but the datetime must at least specify up to the day (e.g. valid: `4545-07-21Z`, `1919-04-05T04:05+09:00`, invalid: `1919Z`). This is a subset of ISO 8601-1:2019 datetime format, but not RFC 3339 (whose time format requires whole seconds precision).
   */
  datetime: string

  /**
   * References to `org.okazu-diary.material.external` records associated with the activity. Leave the array empty if it is known that there is no applicable material. Omit the property if the materials are uncertain. Although this property uses a `strongRef` to make a reference to an external repository reliable to some extent, it is recommended that you copy the record to your own repository if you want to reference a record from another repository.
   */
  subjects?: RepoStrongRef.Main[]

  /**
   * User-specified tags for the activity.
   */
  tags?: MaterialDefs.Tag[]

  /**
   * Remarks on the activity.
   */
  note?: string

  /**
   * Self-label values for this post. Effectively content warnings for the note and tags.
   */
  labels?: l.$Typed<LabelDefs.SelfLabels> | l.Unknown$TypedObject

  /**
   * Indicates the human language of the entry's primary text content and default language for entry tags, overriding the `lang` property from the actor profile record.
   */
  lang?: l.LanguageString

  /**
   * If `true`, indicates that there may have been unrecorded activities since the last entry, so that the data in the meantime are not reliable for statistical purposes.
   */
  hadHiatus?: boolean

  /**
   * Indicates the intended audience of the entry. A `public` entry (default) is fully public. An `unlisted` entry should not be listed in public profile feeds.
   */
  visibility?: 'public' | 'unlisted' | l.UnknownString

  /**
   * Reference to another `org.okazu-diary.feed.entry` record or an `org.okazu-diary.material.collectionItem` record from this entry is derived.
   */
  via?: RepoStrongRef.Main
}

export type { Main }

/** A diary entry to record a self-gratification activity. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    datetime: /*#__PURE__*/ l.string(),
    subjects: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
          (() => RepoStrongRef.main) as any,
        ),
        { maxLength: 16 },
      ),
    ),
    tags: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<MaterialDefs.Tag>((() => MaterialDefs.tag) as any),
        { maxLength: 64 },
      ),
    ),
    note: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 5000, maxGraphemes: 500 }),
    ),
    labels: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.typedUnion(
        [
          /*#__PURE__*/ l.typedRef<LabelDefs.SelfLabels>(
            (() => LabelDefs.selfLabels) as any,
          ),
        ],
        false,
      ),
    ),
    lang: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'language' }),
    ),
    hadHiatus: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.withDefault(/*#__PURE__*/ l.boolean(), false),
    ),
    visibility: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.withDefault(
        /*#__PURE__*/ l.string<{ knownValues: ['public', 'unlisted'] }>(),
        'public',
      ),
    ),
    via: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
        (() => RepoStrongRef.main) as any,
      ),
    ),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
