/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'
import * as LabelDefs from '../../../com/atproto/label/defs.defs.js'

const $nsid = 'org.okazu-diary.actor.profile'

type $nsid = typeof $nsid

export { $nsid }

/** A declaration of an Okazu-Diary.org profile. If the repository has an `app.bsky.actor.profile` record, the application may substitute omitted properties of this record with the counterpart properties from that record, except for those not defined in the bsky Lexicon and the `createdAt` and `labels` properties. An empty string or `null` does not count as "omitted". */
type Main = {
  $type: 'org.okazu-diary.actor.profile'
  displayName?: string | null

  /**
   * Free-form profile description text.
   */
  description?: string | null
  website?: l.UriString | null

  /**
   * Small image to be displayed on the profile. AKA, 'profile picture'. Even though the Okazu-Diary.org applications are primarily intended for sharing sensitive materials, the profile picture must be safe for general audience.
   */
  avatar?: l.BlobRef | null

  /**
   * Self-label values, specific to the Okazu-Diary.org application, on the overall account.
   */
  labels?: l.$Typed<LabelDefs.SelfLabels> | l.Unknown$TypedObject | null

  /**
   * Indicates the user's primary human language, used in the profile and entries.
   */
  lang?: l.LanguageString

  /**
   * List of references to profile records from external Lexicons to link from this profile, such as Bluesky profile. These links are intended to be displayed separately from the `website` link as "trusted" links, so the application should only display links to profiles that can be verified to be controlled by the same actor as the owner of this record. Typically, those are records that belong to the same repository as this record.
   */
  alsoKnownAs?: l.AtUriString[]
  createdAt?: l.DatetimeString | null
}

export type { Main }

/** A declaration of an Okazu-Diary.org profile. If the repository has an `app.bsky.actor.profile` record, the application may substitute omitted properties of this record with the counterpart properties from that record, except for those not defined in the bsky Lexicon and the `createdAt` and `labels` properties. An empty string or `null` does not count as "omitted". */
const main = /*#__PURE__*/ l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  /*#__PURE__*/ l.object({
    displayName: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.nullable(
        /*#__PURE__*/ l.string({ maxGraphemes: 64, maxLength: 640 }),
      ),
    ),
    description: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.nullable(
        /*#__PURE__*/ l.string({ maxGraphemes: 256, maxLength: 2560 }),
      ),
    ),
    website: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.nullable(/*#__PURE__*/ l.string({ format: 'uri' })),
    ),
    avatar: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.nullable(
        /*#__PURE__*/ l.blob({
          accept: ['image/png', 'image/jpeg'],
          maxSize: 1000000,
        }),
      ),
    ),
    labels: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.nullable(
        /*#__PURE__*/ l.typedUnion(
          [
            /*#__PURE__*/ l.typedRef<LabelDefs.SelfLabels>(
              (() => LabelDefs.selfLabels) as any,
            ),
          ],
          false,
        ),
      ),
    ),
    lang: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'language' }),
    ),
    alsoKnownAs: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ format: 'at-uri' })),
    ),
    createdAt: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.nullable(/*#__PURE__*/ l.string({ format: 'datetime' })),
    ),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
