/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'

const $nsid = 'org.okazu-diary.authFull'

type $nsid = typeof $nsid

export { $nsid }

const main = /*#__PURE__*/ l.permissionSet(
  $nsid,
  [
    /*#__PURE__*/ l.permission('repo', {
      action: ['create', 'update', 'delete'],
      collection: [
        'org.okazu-diary.actor.profile',
        'org.okazu-diary.feed.entry',
        'org.okazu-diary.feed.like',
        'org.okazu-diary.material.collection',
        'org.okazu-diary.material.collectionItem',
        'org.okazu-diary.material.external',
      ],
    }),
  ],
  {
    title: 'Full Okazu-Diary.org App Permissions',
    'title:lang': { ja: 'Okazu-Diary.orgアプリへの完全なアクセス権' },
    detail: 'Manage all Okazu-Diary.org application data.',
    'detail:lang': {
      ja: 'Okazu-Diary.orgアプリケーションの全てのデータを管理します。',
    },
  },
)

export { main }
